path_data:   './data/data.txt'
path_last:   './data/last.txt'
url_post:    'http://localhost:4567/upload'
url: 		 'http://info.unlp.edu.ar'
id:  		 '1'
name: 		 'UNLP - Informatica'
adress: 	 '50 y 120'
lat: 		 '-34.903933'
long: 		 '-57.937431'